import { BookData } from "@/modules/books/types/book.types";
import bookPhoto from "./assets/placeholder.png";

export const mockBooks: BookData[] = [
  {
    id: "1",
    name: "1984",
    author: "Джордж Орвелл",
    createdAt: new Date("2025-01-15").toISOString(),
    ownerEmail: "ivan.petrov@example.com",
    ownerId: "user1",
    ownerName: "Іван Петров",
    category: "Класична література",
    city: "Київ",
  },
  {
    id: "2",
    name: "Гаррі Поттер і Філософський камінь",
    author: "Дж. К. Роулінг",
    createdAt: new Date("2025-02-01").toISOString(),
    ownerEmail: "maria.shevchenko@example.com",
    ownerId: "user2",
    ownerName: "Марія Шевченко",
    category: "Фентезі",
    city: "Львів",
  },
  {
    id: "3",
    name: "Sapiens: Коротка історія людства",
    author: "Юваль Ной Харарі",
    createdAt: new Date("2025-01-20").toISOString(),
    ownerEmail: "oleksandr.kovalenko@example.com",
    ownerId: "user3",
    ownerName: "Олександр Коваленко",
    category: "Наукова література",
    city: "Одеса",
  },
  {
    id: "4",
    name: "Тіні забутих предків",
    author: "Михайло Коцюбинський",
    createdAt: new Date("2025-02-05").toISOString(),
    ownerEmail: "anna.honchar@example.com",
    ownerId: "user4",
    ownerName: "Анна Гончар",
    category: "Українська класика",
    city: "Харків",
  },
  {
    id: "5",
    name: "Atomic Habits",
    author: "Джеймс Клір",
    createdAt: new Date("2025-01-28").toISOString(),
    ownerEmail: "dmytro.melnyk@example.com",
    ownerId: "user5",
    ownerName: "Дмитро Мельник",
    category: "Саморозвиток",
    city: "Дніпро",
  },
];
